---@meta _

---@alias Minecraft.entityID string
---| "minecraft:allay"                  # Allay
---| "minecraft:area_effect_cloud"      # Area Effect Cloud
---| "minecraft:armor_stand"            # Armor Stand
---| "minecraft:arrow"                  # Arrow and Tipped Arrow
---| "minecraft:axolotl"                # Axolotl
---| "minecraft:bat"                    # Bat
---| "minecraft:bee"                    # Bee
---| "minecraft:blaze"                  # Blaze
---| "minecraft:block_display"          # Block Display
---| "minecraft:boat"                   # Boat
---| "minecraft:camel"                  # Camel
---| "minecraft:cat"                    # Cat
---| "minecraft:cave_spider"            # Cave Spider
---| "minecraft:chest_boat"             # Boat with Chest
---| "minecraft:chest_minecart"         # Minecart with Chest
---| "minecraft:chicken"                # Chicken
---| "minecraft:cod"                    # Cod
---| "minecraft:command_block_minecart" # Minecart with Command Block
---| "minecraft:cow"                    # Cow
---| "minecraft:creeper"                # Creeper
---| "minecraft:dolphin"                # Dolphin
---| "minecraft:donkey"                 # Donkey
---| "minecraft:dragon_fireball"        # Dragon Fireball
---| "minecraft:drowned"                # Drowned
---| "minecraft:egg"                    # Egg
---| "minecraft:elder_guardian"         # Elder Guardian
---| "minecraft:end_crystal"            # End Crystal
---| "minecraft:ender_dragon"           # Ender Dragon
---| "minecraft:ender_pearl"            # Ender Pearl
---| "minecraft:enderman"               # Enderman
---| "minecraft:endermite"              # Endermite
---| "minecraft:entity_display"         # Entity Display
---| "minecraft:evoker"                 # Evoker
---| "minecraft:evoker_fangs"           # Evoker Fangs
---| "minecraft:experience_bottle"      # Bottle o' Enchanting
---| "minecraft:experience_orb"         # Experience Orb
---| "minecraft:eye_of_ender"           # Eye of Ender
---| "minecraft:falling_block"          # Falling Block
---| "minecraft:fireball"               # Fireball
---| "minecraft:firework_rocket"        # Firework Rocket
---| "minecraft:fishing_bobber"         # Fishing Bobber
---| "minecraft:fox"                    # Fox
---| "minecraft:frog"                   # Frog
---| "minecraft:furnace_minecart"       # Minecart with Furnace
---| "minecraft:ghast"                  # Ghast
---| "minecraft:giant"                  # Giant
---| "minecraft:glow_squid"             # Glow Squid
---| "minecraft:goat"                   # Goat
---| "minecraft:guardian"               # Guardian
---| "minecraft:hoglin"                 # Hoglin
---| "minecraft:hopper_minecart"        # Minecart with Hopper
---| "minecraft:horse"                  # Horse
---| "minecraft:husk"                   # Husk
---| "minecraft:illusioner"             # Illusioner
---| "minecraft:interaction"            # Interaction
---| "minecraft:iron_golem"             # Iron Golem
---| "minecraft:item"                   # Item
---| "minecraft:item_display"           # Item Display
---| "minecraft:item_frame"             # Item Frame
---| "minecraft:leash_knot"             # Leash Knot
---| "minecraft:lightning_bolt"         # Lightning Bolt
---| "minecraft:llama"                  # Llama
---| "minecraft:llama_spit"             # Llama Spit
---| "minecraft:magma_cube"             # Magma Cube
---| "minecraft:marker"                 # Marker
---| "minecraft:minecart"               # Minecart
---| "minecraft:mooshroom"              # Mooshroom
---| "minecraft:mule"                   # Mule
---| "minecraft:ocelot"                 # Ocelot
---| "minecraft:painting"               # Painting
---| "minecraft:panda"                  # Panda
---| "minecraft:parrot"                 # Parrot
---| "minecraft:phantom"                # Phantom
---| "minecraft:pig"                    # Pig
---| "minecraft:piglin"                 # Piglin
---| "minecraft:piglin_brute"           # Piglin Brute
---| "minecraft:pillager"               # Pillager
---| "minecraft:polar_bear"             # Polar Bear
---| "minecraft:potion"                 # Potion
---| "minecraft:pufferfish"             # Pufferfish
---| "minecraft:rabbit"                 # Rabbit
---| "minecraft:ravager"                # Ravager
---| "minecraft:salmon"                 # Salmon
---| "minecraft:sheep"                  # Sheep
---| "minecraft:shulker"                # Shulker
---| "minecraft:shulker_bullet"         # Shulker Bullet
---| "minecraft:silverfish"             # Silverfish
---| "minecraft:skeleton"               # Skeleton
---| "minecraft:skeleton_horse"         # Skeleton Horse
---| "minecraft:slime"                  # Slime
---| "minecraft:small_fireball"         # Small Fireball
---| "minecraft:sniffer"                # Sniffer
---| "minecraft:snow_golem"             # Snow Golem
---| "minecraft:snowball"               # Snowball
---| "minecraft:spawner_minecart"       # Minecart with Monster Spawner
---| "minecraft:spectral_arrow"         # Spectral Arrow
---| "minecraft:spider"                 # Spider
---| "minecraft:squid"                  # Squid
---| "minecraft:stray"                  # Stray
---| "minecraft:strider"                # Strider
---| "minecraft:tadpole"                # Tadpole
---| "minecraft:tnt"                    # Primed TNT
---| "minecraft:tnt_minecart"           # Minecart with TNT
---| "minecraft:trader_llama"           # Trader Llama
---| "minecraft:trident"                # Trident
---| "minecraft:tropical_fish"          # Tropical Fish
---| "minecraft:turtle"                 # Turtle
---| "minecraft:vex"                    # Vex
---| "minecraft:villager"               # Villager
---| "minecraft:vindicator"             # Vindicator
---| "minecraft:wandering_trader"       # Wandering Trader
---| "minecraft:warden"                 # Warden
---| "minecraft:witch"                  # Witch
---| "minecraft:wither"                 # Wither
---| "minecraft:wither_skeleton"        # Wither Skeleton
---| "minecraft:wither_skull"           # Wither Skull
---| "minecraft:wolf"                   # Wolf
---| "minecraft:zoglin"                 # Zoglin
---| "minecraft:zombie"                 # Zombie
---| "minecraft:zombie_horse"           # Zombie Horse
---| "minecraft:zombie_villager"        # Zombie Villager
---| "minecraft:zombified_piglin"       # Zombified Piglin
